### ISSUE TITLE
Some questions about the implement.

### ISSUE THREAD

**Issue by WhatAShot** [lucidrains/reformer-pytorch#113]
Thank you for your implement. It is helpful to me. However, I still have some questions about the details:
**Q1:** What is the meaning of the undo_sort? 
https://github.com/lucidrains/reformer-pytorch/blob/b7dab93dd634380a655ed65c1fda03e83e3c1a96/reformer_pytorch/reformer_pytorch.py#L276

**Q2:** There are many rounds (default by M rounds) in hashing for the input feature (text), and generate an M dimensional hash vector. However, I think we want only one "chunk split" in an attention head. How to use "a hash vector of M dimension" to build just ONE "chunk split", since the hashing results in different rounds are independent? Did I get it wrong? (There is M "chunk split" in an attention head?) I can not find the key codes to fuse the hashing results from various rounds. 

Thank you in advance!

**Comment by lucidrains** [comment]
@WhatAShot Hi Ronnie, and thanks for your interest in the library!

Q1 - The `undo_sort` variable keeps track of the indices of each token after they have been sorted for LSH attention, so that we can resort the tokens back to their original order at a later time https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L398

Q2 - If your 'chunk split' is referring to the each of the hashing rounds, all the hashing rounds are actually done in one go in each attention head. The results of each hashing round is reconstituted at this line here https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L401 (dimension `total_hashes`) and is 'fused' at https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L408

**Comment by WhatAShot** [comment]
Thank you!
