### ISSUE TITLE
Feedforward and attention dropout?

### ISSUE THREAD

**Issue by erickrf** [lucidrains/reformer-pytorch#55]
I noticed there is no dropout in the feedforward layers, nor after the attention. Is there any reason for that?

**Comment by lucidrains** [comment]
@erickrf Hi again, honestly it's because dropouts elsewhere hasn't really affected anything I've been working on. I've added feedforward dropout just now, you can set it with the keyword `ff_dropout`. Is attention dropout done right after the output of attention layer, prior to the residual being added?

**Comment by erickrf** [comment]
I can imagine that FF dropout will have a limited effect given the amount of other regularizations already present in the model.
I was looking at the implementation in Open NMT, and at least there they apply attention dropout where you mentioned.

**Comment by lucidrains** [comment]
@erickrf ok, i'll add it there as well

**Comment by lucidrains** [comment]
@erickrf just released a new version with post attention dropout https://github.com/lucidrains/reformer-pytorch/commit/e0b17c78084e4124267f46d467f5d1027959ba26 let me know if it works for you!
