### ISSUE TITLE
a typo regarding kwargs

### ISSUE THREAD

**Issue by xuanqing94** [lucidrains/reformer-pytorch#79]
https://github.com/lucidrains/reformer-pytorch/blob/352214dc4d2fb13c6018706ec226e60145a7c857/reformer_pytorch/generative_tools.py#L49

Should be `pop('input_mask', None)`, I guess?

And could you please give a pointer on how to reproduce (some of) the results in reformer paper? such as enwiki8-64k training & testing scripts?

**Comment by xuanqing94** [comment]
It looks like `examples/enwik8_simple/train.py` is what I need, can you confirm this?

**Comment by lucidrains** [comment]
oh indeed, i fixed that in the newest version!

and yes to your second question!

Just so you know, after trying to make Reformer work, I am mostly abandoning this project due to its poor performance on a variety of tasks. (https://github.com/lucidrains/reformer-pytorch/issues/69) The biggest takeaway for Reformer is that reversibility works for Transformers, and I will likely apply it to my new project replicating https://arxiv.org/abs/2002.11296 , which seems to work much better than Reformer.

**Comment by xuanqing94** [comment]
@lucidrains Fascinating! Looking forward to your new project!
